#
#	Makefile のターゲットシステム依存部（EZ-KIT lite BF592用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/config/$(CPU)/_common_bf592 \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR) :$(SRCDIR)/config/$(CPU)/$(SYS) :$(SRCDIR)/config/$(CPU)/_common_bf592 :$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS := $(KERNEL_COBJS) chip_config.o uart.o chip_debugboot.o chip_dump.o


#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/_common_bf592/bf592elf.ld

